version: "3.9"
services:
  backend:
    build: .
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; node app.js'
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - net
  db:
    image: mariadb:10.6.4
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net
networks:
  net:
    driver: bridge