name: Unit-Test

on:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Build and test
        run: npm install && npm run build-test